name: Build Test

on: [push]

jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
        
    - name: Setup Godot
      run: |
        mkdir .mono/assemblies/Debug/
        Invoke-WebRequest -OutFile ass.zip 'https://downloads.tuxfamily.org/godotengine/3.2/mono/Godot_v3.2-stable_mono_win64.zip'
        Expand-Archive -Path .\ass.zip -DestinationPath "godot"
        Move "godot\Godot_v3.2-stable_mono_win64\GodotSharp\Api\Debug\" ".mono/assemblies/Debug/"
        Move "godot\Godot_v3.2-stable_mono_win64\GodotSharp\Api\Release\" ".mono/assemblies/Release/"
    - name: Build with dotnet
      run: dotnet build
